### ISSUE TITLE
Delete SCL files

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#59] opened 2021-09-09 11:05 UTC
As a CoMPAS user
I would like to able to remove SCL files form the database using a button
So I can clean up unused SCL configuration files

Acceptance criteria:
Button to remove versions (OpenSCD GUI)

**Comment by dlabordus** [comment] 2021-09-15 13:07
Duplicate of #51

**Closed** 2021-09-15 13:06 UTC
