### ISSUE TITLE
User gets wait icon

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-open-scd#70] opened 2021-09-24 08:23 UTC
User get an wait icon after editing for a while:
![image](https://user-images.githubusercontent.com/7427358/134642132-d1ba4bce-46c6-417d-a528-5e1d0fcdb164.png)

user is afraid of losing data

**Comment by Sander3003** [comment] 2021-09-29 13:42
@laurentjg can you state the steps for getting this error?
Was is a new file?
Did you saw the save as dialog?

**Comment by Laurentjg** [comment] 2021-09-29 15:31
Hi @Sander3003, I tried to reproduce it, but I didn't get the same behavior, but other issues this time. Probably pointing to the same direction: a connection loss to CoMPAS. What I did: I opened OPENSCD with CoMPAS, opened a file from CoMPAS, added a bay and a component and waited for 1 hour. After that the following errors appears (I tried 3 times). 
I also tried to open a project from CoMPAS, but that also resulted in a loading-screen only. See pictures below. I hope this helps.
I
![CompasSaveErr1](https://user-images.githubusercontent.com/36268718/135300243-1bd20340-b900-48b3-8b13-53629ab11c11.PNG)
![CompasSaveErr2](https://user-images.githubusercontent.com/36268718/135300266-87949686-5372-4b5c-a196-105ecf8224d3.PNG)
![CompasOpenErr1](https://user-images.githubusercontent.com/36268718/135300286-a2b94aef-a515-40f6-976c-dec3901014b1.PNG)

**Comment by Sander3003** [comment] 2021-09-30 06:30
Thanks for the feedback!

**Comment by dlabordus** [comment] 2021-10-04 10:26
It doesn't seem that the original issue is caused because of authorization issues. It should then be more something like the screencaptures in the comment (https://github.com/com-pas/compas-open-scd/issues/70#issuecomment-930288649).

The authorizations issues we want to solve with issue 74 (https://github.com/com-pas/compas-open-scd/issues/74). Make some kind of modal panels informing the user that session is about to expire. This way we hope to solve these issue.

So we will close this issue and continue in issue 74 for solving the authorization problems.

**Closed by dlabordus** 2021-10-04 10:26 UTC
Labels: bug
